name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 plotly yfinance pandas numpy pytest ruff

    - name: Run tests
      run: |
        pytest unit_tests.py -v

    - name: Create Release Notes
      id: release_notes
      run: |
        echo "## 市場分析システム リリース" > release_notes.md
        echo "" >> release_notes.md
        echo "### 主な機能" >> release_notes.md
        echo "- シナリオテキストからの自動解析" >> release_notes.md
        echo "- Yahoo Finance からの市場データ取得" >> release_notes.md
        echo "- Plotly インタラクティブチャート" >> release_notes.md
        echo "- SQLite データベース永続化" >> release_notes.md
        echo "- PyQt6 GUI アプリケーション" >> release_notes.md
        echo "" >> release_notes.md
        echo "### インストール方法" >> release_notes.md
        echo "\`\`\`bash" >> release_notes.md
        echo "pip install PyQt6 plotly yfinance pandas numpy" >> release_notes.md
        echo "python main_app.py" >> release_notes.md
        echo "\`\`\`" >> release_notes.md

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release_notes.md
        files: |
          scenario_parser.py
          database_manager.py
          chart_renderer.py
          data_fetcher.py
          main_app.py
          readme_complete.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-artifact@v4
      with:
        name: release-package-${{ github.ref_name }}
        path: |
          *.py
          *.md
